spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: a3df50744b5b80fb1c07fcae6302b457
custom:
  paymentSecretKey: 'test_ck_0RnYX2w532wx0qPwM44gVNeyqApQ:';